/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1pemvis;

import javax.swing.JOptionPane;

/**
 *
 * @author 62813
 */
public class quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form quiz1
     */
    public quiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        uang = new javax.swing.JTextField();
        etotal = new javax.swing.JTextField();
        ejumlah = new javax.swing.JTextField();
        eharga = new javax.swing.JTextField();
        menu = new javax.swing.JComboBox<>();
        pesanan = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        pesan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        bayar = new javax.swing.JButton();
        Kembalianuang = new javax.swing.JLabel();
        Uang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        Pesanan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("COFFEE SHOP WULAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, -1));
        getContentPane().add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 110, -1));
        getContentPane().add(etotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 110, -1));
        getContentPane().add(ejumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 120, -1));

        eharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ehargaActionPerformed(evt);
            }
        });
        getContentPane().add(eharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, -1));

        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Menu", "Cappucino", "Latte", "Americano", "Expreso" }));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, -1));
        getContentPane().add(pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, -1));

        keluar.setBackground(new java.awt.Color(102, 255, 51));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        pesan.setBackground(new java.awt.Color(255, 255, 51));
        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        hapus.setBackground(new java.awt.Color(255, 51, 51));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        bayar.setBackground(new java.awt.Color(0, 204, 204));
        bayar.setText("Total");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        Kembalianuang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Kembalianuang.setText("Uang Kembali :");
        getContentPane().add(Kembalianuang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        Uang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Uang.setText("Uang Bayar     :");
        getContentPane().add(Uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("=======================");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        Jumlah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jumlah.setText("Jumlah Pesan :");
        getContentPane().add(Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        TOTAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TOTAL.setText("Total Bayar     :");
        getContentPane().add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        Harga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Harga.setText("Harga              :");
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        Pesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pesanan.setText("Pesanan          :");
        getContentPane().add(Pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Menu               :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1pemvis/c85dbaaced44cca165f230dbb9a89611.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        switch (menu.getSelectedIndex()){
            case 1:
            {
                pesanan.setText(String.valueOf("Cappucino"));
                eharga.setText(String.valueOf("10000"));
            }
            break;
            case 2:
            {
                pesanan.setText(String.valueOf("Latte"));
                eharga.setText(String.valueOf("13000"));
                
            }
            break;
            case 3:
            {
                pesanan.setText(String.valueOf("Americano"));
                eharga.setText(String.valueOf("14000"));
            }
            break;
            case 4:
            {
                pesanan.setText(String.valueOf("Expreso"));
                eharga.setText(String.valueOf("12000"));
            }
            break;
     
    }
    
    }//GEN-LAST:event_menuActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
        double harga, jumlah, total;
            harga = Double.parseDouble(eharga.getText());
            jumlah = Double.parseDouble(ejumlah.getText());
            total = harga * jumlah;
            etotal.setText(String.valueOf(total));
    }//GEN-LAST:event_bayarActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        // TODO add your handling code here:
        double harga, bayar, hasil;
            harga = Double.parseDouble(etotal.getText());
            bayar = Double.parseDouble(uang.getText());
            hasil = bayar - harga;
            kembalian.setText(String.valueOf(hasil));
    }//GEN-LAST:event_pesanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        menu.setSelectedIndex(0);
        pesanan.setText(" ");
        eharga.setText(" ");
        ejumlah.setText(" ");
        etotal.setText(" ");
        uang.setText(" ");
        kembalian.setText(" ");
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "TERIMA KASIH");
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void ehargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ehargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ehargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel Jumlah;
    private javax.swing.JLabel Kembalianuang;
    private javax.swing.JLabel Pesanan;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel Uang;
    private javax.swing.JButton bayar;
    private javax.swing.JTextField eharga;
    private javax.swing.JTextField ejumlah;
    private javax.swing.JTextField etotal;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembalian;
    private javax.swing.JComboBox<String> menu;
    private javax.swing.JButton pesan;
    private javax.swing.JTextField pesanan;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
